const projectDetails={olist:{type:"POWER BI / E-COMMERCE",title:"Olist Retail Analytics",summary:"A Power BI model over 100,000 Brazilian marketplace orders. Delivery speed — not product mix — turned out to be the strongest driver of customer satisfaction.",focus:"Delivery performance, category concentration, repeat purchase",result:"Late delivery costs 1.73 review stars",stack:"Power BI · Power Query (M) · DAX",link:"case-studies/olist-retail-analytics.html"},ghana:{type:"POWER QUERY / DATA QUALITY",title:"Ghana Regional Sales",summary:"Two regional sales extracts shared four regions with different values because the second restated them. Appending the files looked reasonable and was wrong.",focus:"Reconciliation, restated records, validated totals",result:"A naive append overstated sales by GHS 725,600 (33%)",stack:"Power Query · Excel · DAX"}};
const cards=[...document.querySelectorAll(".project-card")], filters=[...document.querySelectorAll(".filter")];
filters.forEach(button=>button.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));button.classList.add("active");const filter=button.dataset.filter;cards.forEach(card=>{card.classList.toggle("hidden",filter!=="all"&&!card.dataset.category.includes(filter))})}));
const modal=document.querySelector("#projectModal"),modalContent=document.querySelector("#projectModalContent");
function openProject(id){const p=projectDetails[id];if(!p)return;const caseStudy=p.link?`<a href="${p.link}" class="button button-ghost modal-case">Read the full case study <span>↗</span></a>`:"";modalContent.innerHTML=`<span class="eyebrow">${p.type}</span><h2>${p.title}</h2><p>${p.summary}</p><div class="modal-grid"><div class="modal-box"><small>ANALYSIS FOCUS</small><strong>${p.focus}</strong></div><div class="modal-box"><small>KEY FINDING</small><strong>${p.result}</strong></div></div><div class="modal-box"><small>TOOLS & METHODS</small><strong>${p.stack}</strong></div><div class="modal-actions">${caseStudy}<a href="#contact" class="button button-primary modal-contact">Talk about a similar project <span>↗</span></a></div>`;modal.classList.remove("hidden");modalContent.querySelector(".modal-contact").addEventListener("click",closeModal)}
function closeModal(){modal.classList.add("hidden")}
cards.forEach(card=>{const trigger=card.querySelector("button.view-project");if(trigger)trigger.addEventListener("click",()=>openProject(card.dataset.project))});
document.querySelector(".modal-close").addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
const contactForm=document.querySelector("#contactForm"),formMessage=document.querySelector("#formMessage"),submitButton=contactForm.querySelector("button[type=submit]"),OWNER_EMAIL="justicennyiimock@gmail.com";
function setStatus(text,state){formMessage.textContent=text;formMessage.className=`form-message ${state||""}`.trim()}
function mailtoFallback(data){const body=`Name: ${data.name}\nEmail: ${data.email}\n\n${data.message}`;return `mailto:${OWNER_EMAIL}?subject=${encodeURIComponent("New message from your portfolio site")}&body=${encodeURIComponent(body)}`}
contactForm.addEventListener("submit",async e=>{e.preventDefault();if(contactForm.querySelector("[name=_honey]").value)return;const data=Object.fromEntries(new FormData(contactForm).entries());submitButton.disabled=true;setStatus("Sending your message…","sending");try{const response=await fetch(contactForm.action,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(data)});const result=await response.json().catch(()=>({}));if(!response.ok||result.success==="false")throw new Error(result.message||"Request failed");setStatus("Thanks — your message is on its way. I’ll reply to you by email soon.","success");contactForm.reset()}catch(error){setStatus("Couldn’t send automatically. ","error");const link=document.createElement("a");link.href=mailtoFallback(data);link.textContent="Email me directly instead ↗";formMessage.appendChild(link)}finally{submitButton.disabled=false}});
document.querySelector(".menu-toggle").addEventListener("click",()=>{const nav=document.querySelector(".desktop-nav");nav.classList.toggle("mobile-open")});

/* Visitor counter -------------------------------------------------------
   Counts unique visits using Abacus (free, no signup, no cookies).
   A visit is only counted once per browser session, so refreshing the page
   does not inflate the number. Later views in the same session just read
   the current total. If the service is unreachable the counter stays hidden. */
const COUNTER_BASE="https://abacus.jasoncameron.dev",COUNTER_NS="bitanyanmi-mlsa-dev-days",COUNTER_KEY="visits-live";
function animateCount(el,target){const duration=900,start=performance.now();function frame(now){const progress=Math.min((now-start)/duration,1),eased=1-Math.pow(1-progress,3);el.textContent=Math.round(target*eased).toLocaleString();if(progress<1)requestAnimationFrame(frame)}requestAnimationFrame(frame)}
(async function showVisitCount(){const wrap=document.querySelector("#visitCounter"),value=document.querySelector("#visitCount");if(!wrap||!value)return;let counted=false;try{counted=sessionStorage.getItem("visit-counted")==="1"}catch(e){}const endpoint=`${COUNTER_BASE}/${counted?"get":"hit"}/${COUNTER_NS}/${COUNTER_KEY}`;try{const response=await fetch(endpoint,{cache:"no-store"});if(!response.ok)throw new Error("counter unavailable");const data=await response.json();if(typeof data.value!=="number")throw new Error("unexpected response");try{sessionStorage.setItem("visit-counted","1")}catch(e){}wrap.hidden=false;animateCount(value,data.value)}catch(error){wrap.hidden=true}})();
