const projectDetails={retail:{type:"POWER BI / RETAIL",title:"Retail Pulse",summary:"A decision-ready Power BI experience for a growing retail team that needed to move from weekly reporting to daily action.",focus:"Sales performance, regional trends, product mix",result:"24% lift in regional sales focus",stack:"Power BI · DAX · Power Query"},operations:{type:"SQL / OPERATIONS",title:"Flow State",summary:"A focused operational analysis that exposed bottlenecks, clarified handoffs, and gave managers a shared view of service flow.",focus:"Cycle time, throughput, bottleneck analysis",result:"18 hours saved per week",stack:"SQL · Excel · Process mapping"},people:{type:"POWER BI / PEOPLE",title:"People Signals",summary:"A human-centered people analytics dashboard designed to help leaders spot retention signals early and respond with context.",focus:"Retention, tenure, engagement indicators",result:"Earlier action on retention risk",stack:"Power BI · DAX · Data modeling"}};
const cards=[...document.querySelectorAll(".project-card")], filters=[...document.querySelectorAll(".filter")];
filters.forEach(button=>button.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));button.classList.add("active");const filter=button.dataset.filter;cards.forEach(card=>{card.classList.toggle("hidden",filter!=="all"&&!card.dataset.category.includes(filter))})}));
const modal=document.querySelector("#projectModal"),modalContent=document.querySelector("#projectModalContent");
function openProject(id){const p=projectDetails[id];modalContent.innerHTML=`<span class="eyebrow">${p.type}</span><h2>${p.title}</h2><p>${p.summary}</p><div class="modal-grid"><div class="modal-box"><small>ANALYSIS FOCUS</small><strong>${p.focus}</strong></div><div class="modal-box"><small>OUTCOME</small><strong>${p.result}</strong></div></div><div class="modal-box"><small>TOOLS & METHODS</small><strong>${p.stack}</strong></div><a href="#contact" class="button button-primary modal-contact">Talk about a similar project <span>↗</span></a>`;modal.classList.remove("hidden");modalContent.querySelector(".modal-contact").addEventListener("click",closeModal)}
function closeModal(){modal.classList.add("hidden")}
cards.forEach(card=>card.querySelector(".view-project").addEventListener("click",()=>openProject(card.dataset.project)));
document.querySelector(".modal-close").addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
const contactForm=document.querySelector("#contactForm"),formMessage=document.querySelector("#formMessage"),submitButton=contactForm.querySelector("button[type=submit]"),OWNER_EMAIL="justicennyiimock@gmail.com";
function setStatus(text,state){formMessage.textContent=text;formMessage.className=`form-message ${state||""}`.trim()}
function mailtoFallback(data){const body=`Name: ${data.name}\nEmail: ${data.email}\n\n${data.message}`;return `mailto:${OWNER_EMAIL}?subject=${encodeURIComponent("New message from your portfolio site")}&body=${encodeURIComponent(body)}`}
contactForm.addEventListener("submit",async e=>{e.preventDefault();if(contactForm.querySelector("[name=_honey]").value)return;const data=Object.fromEntries(new FormData(contactForm).entries());submitButton.disabled=true;setStatus("Sending your message…","sending");try{const response=await fetch(contactForm.action,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(data)});const result=await response.json().catch(()=>({}));if(!response.ok||result.success==="false")throw new Error(result.message||"Request failed");setStatus("Thanks — your message is on its way. I’ll reply to you by email soon.","success");contactForm.reset()}catch(error){setStatus("Couldn’t send automatically. ","error");const link=document.createElement("a");link.href=mailtoFallback(data);link.textContent="Email me directly instead ↗";formMessage.appendChild(link)}finally{submitButton.disabled=false}});
document.querySelector(".menu-toggle").addEventListener("click",()=>{const nav=document.querySelector(".desktop-nav");nav.classList.toggle("mobile-open")});
