const careers = [
  {id:"product-designer",title:"Product Designer",category:"Creative",icon:"✦",tone:"violet",description:"Shape digital experiences that make everyday life simpler, clearer, and more delightful.",salary:"$88k – $145k",growth:"High growth",skills:["Empathy","Visual thinking","Prototyping"],why:"You get to blend creativity with problem-solving, turning real human needs into products people love to use."},
  {id:"data-scientist",title:"Data Scientist",category:"Technology",icon:"⌁",tone:"blue",description:"Turn complex data into the insights that help teams make smarter, bolder decisions.",salary:"$102k – $172k",growth:"Very high growth",skills:["Curiosity","Python","Storytelling"],why:"A great fit if you love finding patterns and asking the question behind the question."},
  {id:"brand-strategist",title:"Brand Strategist",category:"Creative",icon:"◒",tone:"orange",description:"Give ambitious brands a distinct voice, point of view, and place in people's lives.",salary:"$70k – $128k",growth:"Steady growth",skills:["Big picture","Writing","Research"],why:"Your ideas can shape how people feel about the products and causes they care about."},
  {id:"climate-analyst",title:"Climate Analyst",category:"Impact",icon:"↗",tone:"green",description:"Use science, policy, and systems thinking to build a more resilient future for everyone.",salary:"$64k – $112k",growth:"Very high growth",skills:["Systems thinking","Research","Collaboration"],why:"Meaningful work for people who want their analytical skills to create tangible change."},
  {id:"developer-advocate",title:"Developer Advocate",category:"People",icon:"<>",tone:"yellow",description:"Build communities and make complex technology feel approachable, useful, and human.",salary:"$90k – $155k",growth:"High growth",skills:["Communication","Tech fluency","Community"],why:"You connect people with possibilities and make sure great tools reach the people who need them."},
  {id:"wellbeing-coach",title:"Wellbeing Coach",category:"People",icon:"♡",tone:"pink",description:"Help people build healthier habits, stronger self-awareness, and a life that feels aligned.",salary:"$52k – $98k",growth:"Growing field",skills:["Listening","Motivation","Care"],why:"A deeply human path for natural encouragers who find energy in helping others grow."}
];
let activeFilter="All", searchTerm="", saved=JSON.parse(localStorage.getItem("dreampath-saved")||"[]");
const grid=document.querySelector("#careerGridItems"), savedGrid=document.querySelector("#savedGrid"), savedCount=document.querySelector("#savedCount"), empty=document.querySelector("#emptyState");
function isSaved(id){return saved.includes(id)}
function careerCard(c){return `<article class="career-card"><div class="career-card-top"><div class="career-icon ${c.tone}">${c.icon}</div><button class="heart-button ${isSaved(c.id)?"saved":""}" data-save="${c.id}" aria-label="${isSaved(c.id)?"Remove":"Save"} ${c.title}">${isSaved(c.id)?"♥":"♡"}</button></div><h3>${c.title}</h3><p>${c.description}</p><div class="career-meta"><span class="tag">${c.category}</span><span class="tag">${c.growth}</span></div><button class="card-link" data-details="${c.id}" aria-label="View ${c.title} details">↗</button></article>`}
function render(){const visible=careers.filter(c=>(activeFilter==="All"||c.category===activeFilter)||(activeFilter==="People"&&c.category==="People")).filter(c=>`${c.title} ${c.description} ${c.category} ${c.skills.join(" ")}`.toLowerCase().includes(searchTerm.toLowerCase()));grid.innerHTML=visible.map(careerCard).join("");empty.classList.toggle("hidden",visible.length>0);renderSaved();savedCount.textContent=saved.length;document.querySelectorAll("[data-save]").forEach(b=>b.addEventListener("click",toggleSave));document.querySelectorAll("[data-details]").forEach(b=>b.addEventListener("click",()=>openCareer(b.dataset.details)))}
function renderSaved(){const list=careers.filter(c=>saved.includes(c.id));savedGrid.innerHTML=list.length?list.map(careerCard).join(""):`<div class="saved-placeholder"><span>♡</span><p>Save a career to start your collection.</p></div>`;savedGrid.querySelectorAll("[data-save]").forEach(b=>b.addEventListener("click",toggleSave));savedGrid.querySelectorAll("[data-details]").forEach(b=>b.addEventListener("click",()=>openCareer(b.dataset.details)))}
function toggleSave(e){const id=e.currentTarget.dataset.save;saved=isSaved(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem("dreampath-saved",JSON.stringify(saved));render()}
function openCareer(id){const c=careers.find(x=>x.id===id);document.querySelector("#modalContent").innerHTML=`<span class="modal-label">${c.category.toUpperCase()} PATH</span><h2 id="modalTitle">${c.title}</h2><p class="modal-lead">${c.description}</p><div class="detail-row"><div class="detail-box"><small>Typical salary</small><strong>${c.salary}</strong></div><div class="detail-box"><small>Outlook</small><strong>${c.growth}</strong></div></div><h3>Why this could be you</h3><p class="modal-lead">${c.why}</p><h3>Skills that shine here</h3><div class="skill-list">${c.skills.map(s=>`<span class="tag">${s}</span>`).join("")}</div><button class="button button-primary" data-modal-save="${c.id}">${isSaved(c.id)?"Remove from saved":"Save this path"} <span>♡</span></button>`;document.querySelector("#careerModal").classList.remove("hidden");document.querySelector("[data-modal-save]").addEventListener("click",e=>{toggleSave({currentTarget:{dataset:{save:e.currentTarget.dataset.modalSave}}});openCareer(id)})}
function closeModals(){document.querySelectorAll(".modal-backdrop").forEach(m=>m.classList.add("hidden"))}
document.querySelector("#searchInput").addEventListener("input",e=>{searchTerm=e.target.value;render()});
document.querySelectorAll(".filter-button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter-button").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeFilter=b.dataset.filter;render()}));
document.querySelector("#clearFilters").addEventListener("click",()=>{searchTerm="";activeFilter="All";document.querySelector("#searchInput").value="";document.querySelectorAll(".filter-button").forEach(x=>x.classList.toggle("active",x.dataset.filter==="All"));render()});
document.querySelectorAll(".modal-close").forEach(b=>b.addEventListener("click",closeModals));document.querySelectorAll(".modal-backdrop").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)closeModals()}));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModals()});
const quizQuestions=[{q:"What kind of problems pull you in?",options:[["Making things clearer and more beautiful","creative"],["Finding patterns in messy information","analytical"],["Helping people feel supported and capable","people"],["Building a healthier, fairer future","impact"]]},{q:"Where do you do your best thinking?",options:[["With a sketchbook and lots of possibilities","creative"],["With data, systems, and a good question","analytical"],["In a room full of curious people","people"],["When the work has a purpose beyond profit","impact"]]},{q:"What would make work feel meaningful?",options:[["A chance to express a fresh point of view","creative"],["Learning something new every week","analytical"],["Seeing someone else grow because of you","people"],["Leaving the world better than you found it","impact"]]}];
let quizStep=0, quizAnswers=[];
function openQuiz(){quizStep=0;quizAnswers=[];renderQuiz();document.querySelector("#quizModal").classList.remove("hidden")}
function renderQuiz(){const content=document.querySelector("#quizContent"),bar=document.querySelector("#quizProgressBar");bar.style.width=`${(quizStep/quizQuestions.length)*100}%`;if(quizStep>=quizQuestions.length){const counts=quizAnswers.reduce((a,x)=>(a[x]=(a[x]||0)+1,a),{}),type=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0],match={creative:careers.find(c=>c.id==="product-designer"),analytical:careers.find(c=>c.id==="data-scientist"),people:careers.find(c=>c.id==="wellbeing-coach"),impact:careers.find(c=>c.id==="climate-analyst")}[type];bar.style.width="100%";content.innerHTML=`<div class="quiz-result"><div class="result-icon">${match.icon}</div><span class="modal-label">YOUR FIRST MATCH</span><h2>${match.title}</h2><p>You've got the kind of energy that thrives where curiosity meets purpose. This path could be a strong place to explore next.</p><div class="result-career"><strong>${match.title}</strong><span>${match.description}</span></div><button class="button button-primary" data-result="${match.id}">Explore this path <span>↗</span></button></div>`;content.querySelector("[data-result]").addEventListener("click",()=>{closeModals();openCareer(match.id)});return}const item=quizQuestions[quizStep];content.innerHTML=`<span class="quiz-step">QUESTION ${quizStep+1} OF ${quizQuestions.length}</span><h2 id="quizTitle" class="quiz-question">${item.q}</h2><div class="quiz-options">${item.options.map(([text,value])=>`<button class="quiz-option" data-answer="${value}">${text}</button>`).join("")}</div>`;content.querySelectorAll("[data-answer]").forEach(b=>b.addEventListener("click",()=>{quizAnswers.push(b.dataset.answer);quizStep++;renderQuiz()}))}
["#startQuizButton","#quizNavButton","#ctaQuizButton"].forEach(sel=>document.querySelector(sel).addEventListener("click",openQuiz));render();
